default_language_version:
  python: python3.9
default_stages:
  - commit
  - push
exclude: .*migrations\/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: requirements-txt-fixer
    - id: name-tests-test
      args: [--django, --pytest, --pytest-test-first]
    - id: file-contents-sorter
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: check-merge-conflict
    - id: check-json
    - id: check-docstring-first
    - id: check-ast

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.279'
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=W503

  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          [
            "-rn",
            "-sn",
            --rcfile=.pylintrc
          ]
        exclude: (tests|.pylintrc|manage.py)
        verbose: true

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: ["click==8.0.4"]
        args:
          - --diff # show format suggestions
          - --line-length=120

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.16
    hooks:
      - id: djlint-django

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.812'
  #   hooks:
  #     - id: mypy
  #       exclude: "[a-zA-Z]*/(migrations)/(.)*"
  #       additional_dependencies: [
  #           djangorestframework-stubs,
  #           django-stubs,
  #       ]
